apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodeapp
  namespace: app # Specify namespace here
  labels:
    app: nodeapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodeapp
  template:
    metadata:
      labels:
        app: nodeapp
    spec:
      containers:
        - name: nodeapp
          image: mikeross23/kuber-nodejs-app:2.0
          ports:
            - containerPort: 3000
