apiVersion: v1
kind: Service
metadata:
  name: nodeapp
  namespace: app # Specify namespace here
spec:
  type: NodePort
  selector:
    app: nodeapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30524 # You can specify a node port or let Kubernetes allocate one
