apiVersion: v1
kind: Service
metadata:
  name: loki
  namespace: monitoring
spec:
  type: NodePort
  ports:
    - port: 3100
      targetPort: 3100
      nodePort: 32000 # Specify a nodePort if necessary
      protocol: TCP
  selector:
    app: loki
